on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: xushuangbin/clusterprofilerdocker
          tag_with_ref: true
          tag_with_sha: true
          tags: 4.0.0
