on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:RELEASE_3_13
    steps:
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          repository: xushuangbin/clusterprofilerdocker
          tag_with_ref: true
          tag_with_sha: true
          tags: 4.0.0
